import { ORDER_STATUSES } from "./constants.js";

export const NOTIFICATION_TYPES = Object.freeze({
    ORDER_CREATED_PENDING: "ORDER_CREATED_PENDING",
    ORDER_CREATED_PRODUCTION: "ORDER_CREATED_PRODUCTION",
    ORDER_CREATED_PACKED: "ORDER_CREATED_PACKED",
    ORDER_CONFIRMED: "ORDER_CONFIRMED",
    ORDER_STATUS_PRODUCTION: "ORDER_STATUS_PRODUCTION",
    ORDER_STATUS_PACKED: "ORDER_STATUS_PACKED",
    ORDER_STATUS_INVOICE: "ORDER_STATUS_INVOICE",
    ORDER_STATUS_SHIPPED: "ORDER_STATUS_SHIPPED",
    ORDER_STATUS_DELIVERED: "ORDER_STATUS_DELIVERED",
    ORDER_STATUS_COMPLETED: "ORDER_STATUS_COMPLETED",
    ORDER_STATUS_CANCELLED: "ORDER_STATUS_CANCELLED",
    ORDER_STATUS_REJECTED: "ORDER_STATUS_REJECTED",
});

export const NOTIFICATION_ROLES = Object.freeze({
    SUPER_ADMIN: "ROLE_SUPER_ADMIN",
    ADMIN: "ROLE_ADMIN",
    MANAGER: "ROLE_MANAGER",
    PRODUCTION: "ROLE_PRODUCTION",
    PACKING: "ROLE_PACKING",
    ACCOUNTS: "ROLE_ACCOUNTS",
    DELIVERY: "ROLE_DELIVERY",
    SALESMAN: "ROLE_SALESMAN",
});

export const NOTIFICATION_TARGET_ROLES = Object.freeze({
    [NOTIFICATION_TYPES.ORDER_CREATED_PENDING]: [
        NOTIFICATION_ROLES.SUPER_ADMIN,
        NOTIFICATION_ROLES.ADMIN,
        NOTIFICATION_ROLES.MANAGER,
    ],
    [NOTIFICATION_TYPES.ORDER_CREATED_PRODUCTION]: [
        NOTIFICATION_ROLES.SUPER_ADMIN,
        NOTIFICATION_ROLES.ADMIN,
        NOTIFICATION_ROLES.MANAGER,
        NOTIFICATION_ROLES.PRODUCTION,
        NOTIFICATION_ROLES.PACKING,
    ],
    [NOTIFICATION_TYPES.ORDER_CREATED_PACKED]: [
        NOTIFICATION_ROLES.SUPER_ADMIN,
        NOTIFICATION_ROLES.ADMIN,
        NOTIFICATION_ROLES.MANAGER,
        NOTIFICATION_ROLES.PACKING,
        NOTIFICATION_ROLES.ACCOUNTS,
    ],
    [NOTIFICATION_TYPES.ORDER_CONFIRMED]: [
        NOTIFICATION_ROLES.SUPER_ADMIN,
        NOTIFICATION_ROLES.ADMIN,
        NOTIFICATION_ROLES.MANAGER,
    ],
    [NOTIFICATION_TYPES.ORDER_STATUS_PRODUCTION]: [
        NOTIFICATION_ROLES.SUPER_ADMIN,
        NOTIFICATION_ROLES.ADMIN,
        NOTIFICATION_ROLES.MANAGER,
        NOTIFICATION_ROLES.PRODUCTION,
        NOTIFICATION_ROLES.PACKING,
    ],
    [NOTIFICATION_TYPES.ORDER_STATUS_PACKED]: [
        NOTIFICATION_ROLES.SUPER_ADMIN,
        NOTIFICATION_ROLES.ADMIN,
        NOTIFICATION_ROLES.MANAGER,
        NOTIFICATION_ROLES.PRODUCTION,
        NOTIFICATION_ROLES.PACKING,
        NOTIFICATION_ROLES.ACCOUNTS,
    ],
    [NOTIFICATION_TYPES.ORDER_STATUS_INVOICE]: [
        NOTIFICATION_ROLES.SUPER_ADMIN,
        NOTIFICATION_ROLES.ADMIN,
        NOTIFICATION_ROLES.MANAGER,
        NOTIFICATION_ROLES.ACCOUNTS,
    ],
    [NOTIFICATION_TYPES.ORDER_STATUS_SHIPPED]: [
        NOTIFICATION_ROLES.SUPER_ADMIN,
        NOTIFICATION_ROLES.ADMIN,
        NOTIFICATION_ROLES.MANAGER,
        NOTIFICATION_ROLES.DELIVERY,
    ],
    [NOTIFICATION_TYPES.ORDER_STATUS_DELIVERED]: [
        NOTIFICATION_ROLES.SUPER_ADMIN,
        NOTIFICATION_ROLES.ADMIN,
        NOTIFICATION_ROLES.MANAGER,
    ],
    [NOTIFICATION_TYPES.ORDER_STATUS_COMPLETED]: [
        NOTIFICATION_ROLES.SUPER_ADMIN,
        NOTIFICATION_ROLES.ADMIN,
        NOTIFICATION_ROLES.MANAGER,
    ],
    [NOTIFICATION_TYPES.ORDER_STATUS_CANCELLED]: [
        NOTIFICATION_ROLES.SUPER_ADMIN,
        NOTIFICATION_ROLES.ADMIN,
        NOTIFICATION_ROLES.MANAGER,
    ],
    [NOTIFICATION_TYPES.ORDER_STATUS_REJECTED]: [
        NOTIFICATION_ROLES.SUPER_ADMIN,
        NOTIFICATION_ROLES.ADMIN,
        NOTIFICATION_ROLES.MANAGER,
    ],
});

export const ORDER_NOTIFICATION_TYPE_BY_STATUS = Object.freeze({
    [ORDER_STATUSES.CONFIRMED]: NOTIFICATION_TYPES.ORDER_CONFIRMED,
    [ORDER_STATUSES.PRODUCTION]: NOTIFICATION_TYPES.ORDER_STATUS_PRODUCTION,
    [ORDER_STATUSES.PACKED]: NOTIFICATION_TYPES.ORDER_STATUS_PACKED,
    [ORDER_STATUSES.INVOICE]: NOTIFICATION_TYPES.ORDER_STATUS_INVOICE,
    [ORDER_STATUSES.SHIPPED]: NOTIFICATION_TYPES.ORDER_STATUS_SHIPPED,
    [ORDER_STATUSES.DELIVERED]: NOTIFICATION_TYPES.ORDER_STATUS_DELIVERED,
    [ORDER_STATUSES.COMPLETED]: NOTIFICATION_TYPES.ORDER_STATUS_COMPLETED,
    [ORDER_STATUSES.CANCELLED]: NOTIFICATION_TYPES.ORDER_STATUS_CANCELLED,
    [ORDER_STATUSES.REJECTED]: NOTIFICATION_TYPES.ORDER_STATUS_REJECTED,
});

export const DEVICE_PLATFORMS = Object.freeze({
    WEB: "web",
    ANDROID: "android",
    IOS: "ios",
});

export const NOTIFICATION_LOG_STATUS = Object.freeze({
    SENT: "SENT",
    FAILED: "FAILED",
    PARTIAL: "PARTIAL",
    SKIPPED: "SKIPPED",
});

export const FIREBASE_INVALID_TOKEN_CODES = new Set([
    "messaging/registration-token-not-registered",
    "messaging/invalid-registration-token",
    "messaging/invalid-argument",
]);

export const FIREBASE_RETRYABLE_ERROR_CODES = new Set([
    "messaging/internal-error",
    "messaging/server-unavailable",
    "messaging/unknown-error",
]);
